acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
acme_google:
    resource: "@AcmeSearchBundle/Controller/DefaultController.php"
    type:     annotation
clip_create:
    resource: "@AcmeSearchBundle/Controller/ClipController.php"
    type:     annotation
tag_create:
    resource: "@AcmeSearchBundle/Controller/TagController.php"
    type:     annotation
